apiVersion: v1
kind: Service
metadata:
  name: goosm-mysql
  labels:
    app: goosm
spec:
  ports:
    - port: 3306
  selector:
    app: goosm
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goosm-pv-claim
  labels:
    app: goosm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goosm-mysql
  labels:
    app: goosm
spec:
  selector:
    matchLabels:
      app: goosm
      tier: goosmmysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: goosm
        tier: goosmmysql
    spec:
      containers:
      - image: mysql:8.0
        name: goosmmysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: goosm-pass
              key: password
        - name: MYSQL_DATABASE
          value: goosm
        - name: MYSQL_USER
          value: goosm
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: goosm-pass
              key: password
        ports:
        - containerPort: 3306
          name: goosmmysql
        volumeMounts:
        - name: goosm-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: goosm-persistent-storage
        persistentVolumeClaim:
          claimName: goosm-pv-claim
